### ISSUE TITLE
System.AggregateException: One or more errors occurred. (Premature 2 parsing surrogate pair)

### ISSUE THREAD

**Issue by SlashNephy** [SlashNephy/TVTComment#3]
https://github.com/noriokun4649/TVTComment/tree/a9b72e674c88201f5ab34c4f256bd39ae4fbae8b
```
Application: TvtComment.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AggregateException: One or more errors occurred. (Premature 2 parsing surrogate pair)
 ---> Sgml.SgmlParseException: Premature 2 parsing surrogate pair
   at Sgml.Entity.Error(String msg, Char ch)
   at Sgml.Entity.ExpandCharEntity()
   at Sgml.SgmlReader.ExpandEntity(StringBuilder sb, Char terminator)
   at Sgml.SgmlReader.ParseText(Char ch, Boolean newtext)
   at Sgml.SgmlReader.ParseMarkup()
   at Sgml.SgmlReader.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at Nichan.ArchivedThreadListRetriever.GetHtml(String url, CancellationToken cancellationToken) in D:\a\TVTest-builder\TVTest-builder\TVTComment\Model\Nichan\ArchivedThreadListRetriever.cs:line 197
   at Nichan.ArchivedThreadListRetriever.GetThreadsCreatedAt(DateTimeOffset startTime, DateTimeOffset endTime, CancellationToken cancellationToken) in D:\a\TVTest-builder\TVTest-builder\TVTComment\Model\Nichan\ArchivedThreadListRetriever.cs:line 124
   at Nichan.PastThreadLister.GetBetween(DateTimeOffset startTime, DateTimeOffset endTime, CancellationToken cancellationToken) in D:\a\TVTest-builder\TVTest-builder\TVTComment\Model\Nichan\PastThreadLister.cs:line 47
   at TVTComment.Model.NichanUtils.AutoPastNichanThreadSelector.Get(ChannelInfo channel, DateTimeOffset time, CancellationToken cancellationToken) in D:\a\TVTest-builder\TVTest-builder\TVTComment\Model\NichanUtils\AutoPastNichanThreadSelector.cs:line 40
   at TVTComment.Model.ChatCollectService.PastNichanChatCollectService.ResCollectLoop(CancellationToken cancellationToken) in D:\a\TVTest-builder\TVTest-builder\TVTComment\Model\ChatCollectService\PastNichanChatCollectService.cs:line 119
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at TVTComment.Model.ChatCollectService.PastNichanChatCollectService.GetOnceASecond(ChannelInfo channel, DateTime time) in D:\a\TVTest-builder\TVTest-builder\TVTComment\Model\ChatCollectService\PastNichanChatCollectService.cs:line 89
--- End of stack trace from previous location ---
   at TVTComment.Model.ChatCollectService.PastNichanChatCollectService.ResCollectLoopTaskExceptionHandler(AggregateException e) in D:\a\TVTest-builder\TVTest-builder\TVTComment\Model\ChatCollectService\PastNichanChatCollectService.cs:line 237
   at TVTComment.Model.ChatCollectService.PastNichanChatCollectService.GetOnceASecond(ChannelInfo channel, DateTime time) in D:\a\TVTest-builder\TVTest-builder\TVTComment\Model\ChatCollectService\PastNichanChatCollectService.cs:line 89
   at TVTComment.Model.ChatCollectService.OnceASecondChatCollectService.GetChats(ChannelInfo channel, DateTime time) in D:\a\TVTest-builder\TVTest-builder\TVTComment\Model\ChatCollectService\OnceASecondChatCollectService.cs:line 24
   at TVTComment.Model.ChatCollectServiceModule.<>c__DisplayClass28_0.<TimerCallback>b__0(Object _) in D:\a\TVTest-builder\TVTest-builder\TVTComment\Model\ChatCollectServiceModule.cs:line 81
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at TVTComment.App.Main()

```

**Comment by SlashNephy** [comment]
https://github.com/noriokun4649/TVTComment/pull/23 により解決しました
